### ISSUE TITLE
Out of sync sometimes removes synced text

### ISSUE THREAD

**Issue by davjs** [overleaf/document-updater#6]
Hi!

I frequently use share-latex together with a classmate on a school wifi that often seem to cause out of sync errors. Sometimes however we have noticed that sharelatex can remove my latest edits when the connection is back even though they had been synced to my friend. This gets very annoying for both of us and should not happen.

**Comment by ShaneKilkelly** [comment]
Hi! I've closed this issue as we've done a lot of work on improving sync over the years. If you encounter any more problems do let us know at support@overleaf.com
