### ISSUE TITLE
Gruntfile.coffee missing

### ISSUE THREAD

**Issue by mickaelbaron** [overleaf/document-updater#60]
Hi, 

I suppose _Gruntfile.coffee_ file is missing to build this project. 

When i'm building a Docker image of Sharelatex, this module isn't built because  _Gruntfile.coffee_ is missing. In this script https://github.com/sharelatex/sharelatex/blob/master/bin/install-services `grunt install` has no effect on the _document-updater_ module.

What do you think about my proposition?

Mickael

**Comment by das7pad** [comment]
The file was removed by @jpallen in [this](https://github.com/sharelatex/document-updater-sharelatex/commit/dc1d52b182502538eb06f4cca7eaaa6f684f21f5) commit.

The `Gruntfile` diff is here: https://github.com/sharelatex/document-updater-sharelatex/commit/dc1d52b182502538eb06f4cca7eaaa6f684f21f5#diff-a35864fcc4749a3b904641b4be9feacf.

I suggest that one of the sharelatex devs runs their [build scripts](https://github.com/sharelatex/sharelatex-dev-environment) on this project again.

---

Is there any chance we could get access to the build scripts?

**Comment by ShaneKilkelly** [comment]
@das7pad closing this one as I think it's been solved for a while.
