### ISSUE TITLE
dtrace.h not found

### ISSUE THREAD

**Issue by ghost** [overleaf/document-updater#7]
Some parts of sharelatex still use

"logger-sharelatex": "git+https://github.com/sharelatex/logger-sharelatex.git#v1.0.0"

which prevents a successful compilation on FreeBSD. I haven't checked, if this is true for OpenBSD.

logger-sharelatex version 1.4.0 seems to work fine, but I haven't done an in-depth check. At least it compiles. Whether there are other problems due to incompatibility with newer versions of logger-sharelatex, I can't say.

Could this perhaps be fixed to use a newer version, thus allowing for the normal install process to work without manual corrections?

**Comment by ShaneKilkelly** [comment]
Just closing this as I think we fixed it a while ago, see https://github.com/overleaf/document-updater/issues/9
