### ISSUE TITLE
Too many redis connections inside docker

### ISSUE THREAD

**Issue by ltronky** [overleaf/document-updater#9]
In the last 2 days I tried to build https://github.com/sharelatex/sharelatex-docker-image to testing purposes on the web component, but I found a strange bug on this component that continuosly generates errors in creating connections with redis and does not responds anymore.
Looking with `netstat` to port `6379` from the inside of the container I notice 1000+ connections  and growing through the time, with only few as `ESTABLISHED` while all the others are in `TIME_WAIT` state.
I didn't notice this behavior running every component separately outside the container.

An other tips: last time I build the system was nearly the June 1st and it was ok. So I tried to build the docker image with all the component on the `HEAD` of the `master` branch, while using this component fixed at this commit 5511e26fd8dab591df683e889781eaa5b3ff9993 and it seems to work fine. So I can suppose the bug has been introduced from than and now.

I hope I was helpful.

**Comment by ShaneKilkelly** [comment]
Just closing this as I think we fixed it a while ago, see https://github.com/overleaf/document-updater/issues/9
